# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mast
pod 'MessageKit'
pod 'SDWebImage'
pod 'ActiveLabel'
pod 'SwiftyStoreKit'

end

target 'MastExtension' do

  use_frameworks!

pod 'SDWebImage'

end
